
name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:


    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.NOICE  }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.

        BUILD_SCRIPT: game.exe





   

  
    
    
     
    
  
       
      
